# Generated by Django 5.0.4 on 2024-04-21 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_photo_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='basket',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_basket', to='shop.product'),
        ),
        migrations.AddField(
            model_name='about',
            name='allmodels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_about', to='shop.allmodels'),
        ),
        migrations.AddField(
            model_name='basket',
            name='allmodels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_basket', to='shop.allmodels'),
        ),
        migrations.AddField(
            model_name='brand',
            name='allmodels',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.allmodels'),
        ),
        migrations.AddField(
            model_name='caruselphoto',
            name='allmodels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_carusel', to='shop.allmodels'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='allmodels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_character', to='shop.allmodels'),
        ),
        migrations.AddField(
            model_name='color',
            name='allmodels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_color', to='shop.allmodels'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='allmodels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_favorite', to='shop.allmodels'),
        ),
        migrations.AddField(
            model_name='model',
            name='allmodels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_model', to='shop.allmodels'),
        ),
        migrations.AddField(
            model_name='news',
            name='allmodels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_news', to='shop.allmodels'),
        ),
        migrations.AddField(
            model_name='order',
            name='allmodels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_order', to='shop.allmodels'),
        ),
        migrations.AddField(
            model_name='photo',
            name='allmodels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_photo', to='shop.allmodels'),
        ),
        migrations.AddField(
            model_name='product',
            name='allmodels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_product', to='shop.allmodels'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='allmodels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_review', to='shop.allmodels'),
        ),
        migrations.AddField(
            model_name='sale',
            name='allmodels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_sale', to='shop.allmodels'),
        ),
    ]
