# Generated by Django 5.0.4 on 2024-04-21 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_allmodels_alter_basket_product_about_allmodels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='allmodels',
        ),
    ]
