# Generated by Django 5.0.4 on 2024-05-02 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_brand_allmodels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='product',
        ),
    ]
